# Generated by Django 6.0.3 on 2026-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ilość'),
        ),
    ]
