# Generated by Django 6.0.3 on 2026-03-18 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_servings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa wydarzenia')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data wydarzenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Zrobione')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_recipes', to='recipes.event')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_entries', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Przepis w wydarzeniu',
                'verbose_name_plural': 'Przepisy w wydarzeniu',
                'ordering': ['added_at'],
                'unique_together': {('event', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='events', through='recipes.EventRecipe', to='recipes.recipe', verbose_name='Przepisy'),
        ),
    ]
